server {
    listen 80;
    server_name aety.ru www.aety.ru;

    client_max_body_size 50M;

    location /static/ {
        alias /var/www/aety/staticfiles/;
    }

    location /media/ {
        alias /var/www/aety/media/;
    }

    location / {
        proxy_pass http://unix:/run/aety/aety.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
