# Generated by Django 6.0.3 on 2026-05-07 12:46

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_roles_options_alter_users_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='main.roles'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_lower_unique'),
        ),
    ]
