# Generated by Django 6.0.3 on 2026-05-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_course_tags_and_lesson_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lessoncomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='material',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='video_url',
        ),
    ]
